'use client';
import {useEffect,useState} from 'react';

type Repo={name:string,full_name:string,default_branch:string,private:boolean};
type Op={path:string,action:string,content:string};
export default function Home(){
 const [repos,setRepos]=useState<Repo[]>([]),[repo,setRepo]=useState(''),[branch,setBranch]=useState('main'),[prompt,setPrompt]=useState(''),[plan,setPlan]=useState<any>(null),[loading,setLoading]=useState(false),[msg,setMsg]=useState('');
 useEffect(()=>{fetch('/api/github/repos').then(r=>r.json()).then(x=>{if(Array.isArray(x))setRepos(x);});},[]);
 const selected=repos.find(r=>r.full_name===repo);
 async function analyze(){if(!selected||!prompt)return;setLoading(true);setMsg('Analyse du dépôt...');setPlan(null);try{const r=await fetch('/api/agent',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({owner:selected.full_name.split('/')[0],repo:selected.name,branch,prompt})});const x=await r.json();if(x.error)throw new Error(x.error);setPlan(x);setMsg('Plan prêt — vérifie les fichiers avant application.')}catch(e){setMsg(String(e));}finally{setLoading(false)}}
 async function apply(){if(!selected||!plan?.operations?.length)return;setLoading(true);setMsg('Écriture sur GitHub...');try{for(const op of plan.operations){const r=await fetch('/api/github/write',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({owner:selected.full_name.split('/')[0],repo:selected.name,path:op.path,content:op.content,message:`ai: ${prompt.slice(0,60)}`,branch})});if(!r.ok)throw new Error(await r.text());}setMsg('✓ Modifications appliquées sur GitHub.');}catch(e){setMsg(String(e));}finally{setLoading(false)}}
 async function newBranch(){if(!selected)return;const name=`ai/${Date.now()}`;const r=await fetch('/api/github/branch',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({owner:selected.full_name.split('/')[0],repo:selected.name,branch:name,base:selected.default_branch})});if(r.ok){setBranch(name);setMsg(`Branche ${name} créée.`)}else setMsg(await r.text())}
 return <main><header><div className="brand"><span className="logo">✦</span><div><b>ChatGPT</b><small> GitHub Agent</small></div></div><a className="github" href="/api/auth/github">🐙 {repos.length?'GitHub connecté':'Connecter GitHub'}</a></header><section className="layout"><aside><h3>Workspace</h3><label>Repository</label><select value={repo} onChange={e=>{setRepo(e.target.value);const r=repos.find(x=>x.full_name===e.target.value);if(r)setBranch(r.default_branch)}}><option value="">Choisir un repo…</option>{repos.map(r=><option key={r.full_name} value={r.full_name}>{r.name}{r.private?' 🔒':''}</option>)}</select><label>Branche</label><div className="row"><input value={branch} onChange={e=>setBranch(e.target.value)}/><button onClick={newBranch} disabled={!repo}>＋</button></div><div className="hint">L’agent peut analyser et modifier les fichiers du dépôt sélectionné.</div></aside><section className="chat"><div className="hero"><div className="orb">✦</div><h1>Que veux-tu construire ?</h1><p>Demande une modification, un bug fix ou une nouvelle fonctionnalité.</p></div><div className="composer"><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Ex : analyse mon projet et corrige le problème de responsive de la sidebar…"/><button onClick={analyze} disabled={loading||!repo||!prompt}>{loading?'Analyse…':'Analyser le projet →'}</button></div>{msg&&<div className="status">{msg}</div>}{plan&&<div className="plan"><div className="planHead"><div><b>{plan.summary||'Plan de modification'}</b><span>{plan.operations?.length||0} fichier(s)</span></div><button onClick={apply} disabled={loading||!plan.operations?.length}>✓ Appliquer</button></div>{plan.operations?.map((op:Op,i)=><details key={i}><summary>✏️ {op.path}</summary><pre>{op.content}</pre></details>)}{plan.notes?.map((n:string,i:number)=><p className="note" key={i}>• {n}</p>)}</div>}</section></section></main>}
